#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  Drive1,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Drive2,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Lift1,          sensorQuadEncoder)
#pragma config(Motor,  port1,           Drive1,        tmotorNone, openLoop)
#pragma config(Motor,  port2,           Drive2,        tmotorNone, openLoop)
#pragma config(Motor,  port3,           Lift1,         tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "functions.h"

	int driveEncoder;
	int liftEncoder;

task main()
{

	while(true)
	{

    setDrive(vexRT[Ch2], vexRT[Ch3]);


		if(vexRT[Btn5U])
			setLiftSpeed(127);
		else if(vexRT[Btn5D])
			setLiftSpeed(-127);
		else
			setLiftSpeed(0);

		if(vexRT[Btn7U] == 1)
		{
			writeDebugStream("drivePID(%d);\r\n", getDriveEncoder());
		}
		if(vexRT[Btn7D] == 1)
		{
			writeDebugStream("liftPID(%d);\r\n", getLiftEncoder());
		}
		if(vexRT[Btn7R] == 1)
		{
			writeDebugStream("gyroTurn(%d);\r\n", getGyro());
		}

		if(vexRT[Btn8U] == 1)
		{
			clearDrive();
		}
		if(vexRT[Btn8D] == 1)
		{
			clearLift();
		}
		if(vexRT[Btn8R] == 1)
		{
			clearGyro();
		}

	}


}
